# Pre-test cleanup: removes all data generated by previous test runs so each
# `gradlew test` invocation starts from a known baseline. Seeded admin/buyer/
# supplier users and their companies are preserved.
#
# Requires:
#   - Docker on PATH (uses the postgres:17-alpine image as a psql client).
#   - Env var DB_PASSWORD matching the application's PostgreSQL password.

$ErrorActionPreference = "Stop"

if (-not $env:DB_PASSWORD -or $env:DB_PASSWORD.Length -eq 0) {
    Write-Host "ERROR: DB_PASSWORD env var is not set." -ForegroundColor Red
    exit 1
}

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Host "ERROR: docker not found on PATH." -ForegroundColor Red
    exit 1
}

$sql = @"
-- Keep flyway_schema_history and seeded admin/buyer/supplier (identified by
-- tax_code 0101234567 and 0107654321) and the three seeded users.
TRUNCATE TABLE
  order_status_history,
  order_items,
  payments,
  orders,
  cart_items,
  carts,
  product_prices,
  products,
  commission_rates,
  system_settings,
  auth_accounts,
  categories
RESTART IDENTITY CASCADE;

DELETE FROM users WHERE username NOT IN ('admin', 'buyer', 'supplier');
DELETE FROM companies WHERE tax_code NOT IN ('0101234567', '0107654321');
"@

Write-Host "[pre-test] Truncating test data..." -ForegroundColor Cyan
docker run --rm --entrypoint psql -e PGPASSWORD=$env:DB_PASSWORD postgres:17-alpine `
    -h host.docker.internal -U postgres -d b2b -c $sql | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: TRUNCATE failed." -ForegroundColor Red
    exit $LASTEXITCODE
}
Write-Host "[pre-test] Done." -ForegroundColor Green

Write-Host "[pre-test] Running gradle test..." -ForegroundColor Cyan
& .\gradlew.bat test --no-daemon
exit $LASTEXITCODE