-- ============================================================================
-- V10__create_system_settings_table.sql
-- B2B Procure System - Create system_settings table and seed initial settings
-- Database: PostgreSQL
-- ============================================================================

CREATE TABLE system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR NOT NULL,
    setting_value VARCHAR NOT NULL,
    description VARCHAR,
    updated_at TIMESTAMP,
    updated_by BIGINT,
    CONSTRAINT uk_system_settings_key UNIQUE (setting_key),
    CONSTRAINT fk_system_settings_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
);

CREATE INDEX idx_system_settings_updated_by ON system_settings (updated_by);

-- Seed initial settings
INSERT INTO system_settings (setting_key, setting_value, description, updated_at, updated_by)
VALUES
('PAYMENT_TIMEOUT_MINUTES', '15', 'Maximum time allowed for Buyer to complete online payment.', CURRENT_TIMESTAMP, NULL),
('SUPPLIER_CONFIRM_TIMEOUT_HOURS', '24', 'Maximum time allowed for Supplier to Confirm or Reject an Order.', CURRENT_TIMESTAMP, NULL)
ON CONFLICT (setting_key) DO NOTHING;
