-- ============================================================================
-- V1__init_schema.sql
-- B2B Procure System - Initial Schema Migration
-- Database: PostgreSQL
-- ============================================================================

-- ============================================================================
-- 1. BẢNG ROLES
-- ============================================================================
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    description VARCHAR,
    CONSTRAINT uk_roles_name UNIQUE (name)
);

-- Seed 3 default system roles
INSERT INTO roles (name, description)
VALUES
('ADMIN', 'System administrator'),
('BUYER', 'Buyer user'),
('SUPPLIER', 'Supplier user');

-- ============================================================================
-- 2. BẢNG COMPANIES
-- ============================================================================
CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    tax_code VARCHAR NOT NULL,
    email VARCHAR,
    phone VARCHAR,
    address VARCHAR,
    company_type VARCHAR,
    status VARCHAR,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_companies_tax_code UNIQUE (tax_code)
);

-- ============================================================================
-- 3. BẢNG CATEGORIES
-- ============================================================================
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    description VARCHAR,
    status VARCHAR,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- ============================================================================
-- 4. BẢNG USERS
-- ============================================================================
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    company_id BIGINT,
    username VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    full_name VARCHAR,
    email VARCHAR NOT NULL,
    phone VARCHAR,
    avatar_url VARCHAR(500),
    cover_image_url VARCHAR(500),
    status VARCHAR,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_users_company FOREIGN KEY (company_id) REFERENCES companies (id)
);

CREATE INDEX idx_users_role_id ON users (role_id);
CREATE INDEX idx_users_company_id ON users (company_id);

-- ============================================================================
-- 5. BẢNG PRODUCTS
-- ============================================================================
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_company_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    sku VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    description TEXT,
    image_url VARCHAR(500),
    stock_quantity INT,
    status VARCHAR,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_products_sku UNIQUE (sku),
    CONSTRAINT fk_products_supplier_company FOREIGN KEY (supplier_company_id) REFERENCES companies (id),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE INDEX idx_products_supplier_company_id ON products (supplier_company_id);
CREATE INDEX idx_products_category_id ON products (category_id);

-- ============================================================================
-- 6. BẢNG PRODUCT_PRICES
-- ============================================================================
CREATE TABLE product_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    min_quantity INT NOT NULL,
    max_quantity INT,
    unit_price DECIMAL(15,2) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_product_prices_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_product_prices_product_id ON product_prices (product_id);

-- ============================================================================
-- 7. BẢNG CARTS
-- ============================================================================
CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_carts_user_id UNIQUE (user_id),
    CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ============================================================================
-- 8. BẢNG CART_ITEMS
-- ============================================================================
CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts (id),
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_cart_items_cart_id ON cart_items (cart_id);
CREATE INDEX idx_cart_items_product_id ON cart_items (product_id);

-- ============================================================================
-- 9. BẢNG ORDERS
-- ============================================================================
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_company_id BIGINT NOT NULL,
    supplier_company_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    order_code VARCHAR NOT NULL,
    status VARCHAR NOT NULL,
    subtotal DECIMAL(15,2),
    commission_rate DECIMAL(5,2),
    commission_amount DECIMAL(15,2),
    total_amount DECIMAL(15,2),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_orders_order_code UNIQUE (order_code),
    CONSTRAINT fk_orders_buyer_company FOREIGN KEY (buyer_company_id) REFERENCES companies (id),
    CONSTRAINT fk_orders_supplier_company FOREIGN KEY (supplier_company_id) REFERENCES companies (id),
    CONSTRAINT fk_orders_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE INDEX idx_orders_buyer_company_id ON orders (buyer_company_id);
CREATE INDEX idx_orders_supplier_company_id ON orders (supplier_company_id);
CREATE INDEX idx_orders_created_by ON orders (created_by);

-- ============================================================================
-- 10. BẢNG ORDER_ITEMS
-- ============================================================================
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(15,2) NOT NULL,
    subtotal DECIMAL(15,2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);
CREATE INDEX idx_order_items_product_id ON order_items (product_id);

-- ============================================================================
-- 11. BẢNG ORDER_STATUS_HISTORY
-- ============================================================================
CREATE TABLE order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    changed_by BIGINT NOT NULL,
    status VARCHAR NOT NULL,
    note TEXT,
    created_at TIMESTAMP,
    CONSTRAINT fk_order_status_history_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_status_history_changed_by FOREIGN KEY (changed_by) REFERENCES users (id)
);

CREATE INDEX idx_order_status_history_order_id ON order_status_history (order_id);
CREATE INDEX idx_order_status_history_changed_by ON order_status_history (changed_by);

-- ============================================================================
-- 12. BẢNG COMMISSION_RATES
-- ============================================================================
CREATE TABLE commission_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate DECIMAL(5,2) NOT NULL,
    effective_from TIMESTAMP,
    created_at TIMESTAMP,
    created_by BIGINT NOT NULL,
    CONSTRAINT fk_commission_rates_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE INDEX idx_commission_rates_created_by ON commission_rates (created_by);
