-- ============================================================================
-- V3__add_auth_accounts.sql
-- B2B Procure System - Add Auth Accounts for OAuth2 Authentication
-- Database: PostgreSQL
-- ============================================================================

-- ============================================================================
-- 1. BẢNG AUTH_ACCOUNTS
-- ============================================================================
CREATE TABLE auth_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR NOT NULL,
    provider_user_id VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_auth_accounts_provider_user UNIQUE (provider, provider_user_id),
    CONSTRAINT fk_auth_accounts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_auth_accounts_user_id ON auth_accounts (user_id);
