-- ============================================================================
-- V9__create_payments_table.sql
-- B2B Procure System - Create payments table
-- Database: PostgreSQL
-- ============================================================================

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    payment_code VARCHAR NOT NULL,
    payment_method VARCHAR NOT NULL,
    status VARCHAR NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    paid_at TIMESTAMP,
    expired_at TIMESTAMP,
    refunded_at TIMESTAMP,
    provider_transaction_id VARCHAR,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_payments_order_id UNIQUE (order_id),
    CONSTRAINT uk_payments_payment_code UNIQUE (payment_code),
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT chk_payments_amount CHECK (amount > 0),
    CONSTRAINT chk_payments_payment_method CHECK (payment_method IN ('ZALOPAY', 'MOMO', 'COD')),
    CONSTRAINT chk_payments_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'EXPIRED', 'REFUND_PENDING', 'REFUNDED'))
);

CREATE INDEX idx_payments_provider_transaction_id ON payments (provider_transaction_id);
